### ISSUE TITLE
Gamult Launch Checklist

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#124]
This is a prioritized launch for iPhones, but let's try and make it for iOS tablets and Android devices (phones and tablets as well) just before the end of the year.

#### iOS
- [x] Add images from Tiago C.
- [x] Close #111 (small info button)
- [x] Close #125 (don't allow change instrument in about screen)
- [x] Close #126 (Remove swipe info from iPad version)
- [x] Test internally
- [x] Github release tag
- [x] Submit RC to Apple Store 
(instructions at https://github.com/Digitopia/PORTOphone-app/wiki/Deploy-instructions)
- [x] Fix multiple minor issues (#129)
- [x] Github release tag
- [x] Submit again to App Store
- [x] Advertise 

#### Android
- [x] Add images from Tiago C.
- [x] Close #111 (small info button)
- [x] Finish #80 (make it work in Android)
- [x] Adopt to tablets
- [x] Test internally
- [x] Github release tag
- [ ] Submit to Google Play
(instructions at https://github.com/Digitopia/PORTOphone-app/wiki/Deploy-instructions)
- [ ] Advertise
